### ISSUE TITLE
feathers-authentication with oauth2 fails after first login when using feathers-mongoose

### ISSUE THREAD

**Issue by iamso** [feathersjs/feathers-mongoose#177]
### Steps to reproduce

- Use the feathers cli to create a new project using the following options:
```bash
What type of API are you making?
◉ REST
◉ Realtime via Socket.io

CORS configuration
❯ Enabled for all domains

What database do you primarily want to use? 
❯ MongoDB 

What authentication providers would you like to support? 
◉ google
```
- Then add google api key and secret to the config file.
- Run the app with `npm start`.
- Navigate to http://localhost:3030/auth/google
- This works fine, you see the default success page with the token
- Now navigate to http://localhost:3030/auth/google again
- And now you'll get the failure message

This is the output from the debugger:
```bash
  feathers-authentication:oauth2 Updating user: [user id would be here] +11m
  feathers-authentication:middleware An authentication error occurred. { GeneralError: Unknown modifier: $__
    at GeneralError.ExtendableBuiltin (/Users/so/Private/_TEST/feathersjs/auth-test/node_modules/feathers-errors/lib/index.js:21:28)
    at GeneralError.FeathersError (/Users/so/Private/_TEST/feathersjs/auth-test/node_modules/feathers-errors/lib/index.js:96:116)
    at new GeneralError (/Users/so/Private/_TEST/feathersjs/auth-test/node_modules/feathers-errors/lib/index.js:281:109)
    at errorHandler (/Users/so/Private/_TEST/feathersjs/auth-test/node_modules/feathers-mongoose/lib/error-handler.js:32:31)
    at process._tickCallback (internal/process/next_tick.js:109:7)
  type: 'FeathersError',
  name: 'GeneralError',
  code: 500,
  className: 'general-error',
  data: undefined,
  errors: {} } +27ms
```

### Expected behavior
The user should be able to login after the first initial login.

### Actual behavior
What actually happens is, that the user is created and logged in the first time, but the next times the user is not logged in because of the before mentioned error.

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
From package.json:
```json
"dependencies": {
    "body-parser": "^1.17.1",
    "compression": "^1.6.2",
    "cors": "^2.8.3",
    "feathers": "^2.1.1",
    "feathers-authentication": "^0.7.12",
    "feathers-configuration": "^0.3.3",
    "feathers-errors": "^2.6.2",
    "feathers-hooks": "^1.8.1",
    "feathers-mongoose": "^3.6.2",
    "feathers-rest": "^1.7.1",
    "feathers-socketio": "^1.5.2",
    "mongoose": "^4.9.2",
    "passport": "^0.3.2",
    "passport-google-oauth20": "^1.0.0",
    "passport-google-token": "^0.1.2",
    "serve-favicon": "^2.4.2",
    "winston": "^2.3.1"
  }
```

**NodeJS version**:
v7.7.4

**Operating System**:
macOS Sierra 10.12.3

**Browser Version**:
Chrome 56.0.2924.87

**Comment by iamso** [comment]
BTW I've tested the same scenario using a clean install from the feathers cli with MariaDB, NeDB and SQLite, using the same google api credentials and it works with all of them, only with feathers-mongoose I get this error.

**Comment by marshallswain** [comment]
Can you try the same thing with the new releases of these modules?  You can use the prerelease version of the CLI.  `npm install feathers-cli@pre -g`  Then `feathers generate app` and `feathers generate authentication`.

**Comment by iamso** [comment]
Ok, so the login now works after the first login. But a few things have changed and/or are missing:

- the config file for production is not updated when generating authentication
- the settings for google auth changed and now the scope can't be inside of permissions and hostedDomain does not work anymore
- and only the googleId is stored in the database, instead of all the user data

I don't know if this is the right place for this feedback, but maybe you can pass it on or point me to the right place.

Oh, and is there a documentation for the new version? I would like to check that out some more.

Thanks

**Comment by marshallswain** [comment]
@iamso The latest docs for the new version are here: https://docs.feathersjs.com/v/auk/.  You'll notice that the docs have seen a lot of updates.

In the new version, the authentication has been split into multiple plugins based on authentication strategy.  
 - The core auth plugin is here: https://docs.feathersjs.com/v/auk/api/authentication/server.html
 - The OAuth2 plugin is here: https://docs.feathersjs.com/v/auk/api/authentication/oauth2.html

The issues you've mentioned would now fit best in this repo: https://github.com/feathersjs/feathers-authentication-oauth2/

**Comment by iamso** [comment]
@marshallswain Thank you. 

But is there any way to solve this in the current version?

**Comment by marshallswain** [comment]
Of course there is.  I'm not sure why it's not working in the first place.  I've created a lot of apps with the same setup minus the Google auth.  I've only used GitHub.  Have you tried other providers?

**Comment by iamso** [comment]
I've tested it with Bitbucket, Facebook, Github, Google and Linkedin, I always get the same error when logging in after the user has been created.

**Comment by iamso** [comment]
@marshallswain any news?

**Comment by marshallswain** [comment]
I'm getting closer to being able to check this.  Have you made any debugging progress?

**Comment by iamso** [comment]
No, not really, but I haven't spent any more time on it, to be honest.

**Comment by daffl** [comment]
My hunch is that this has something to do with https://github.com/feathersjs/feathers-authentication-oauth2/pull/20
