### ISSUE TITLE
how to catch MongoError

### ISSUE THREAD

**Issue by wuyuanyi135** [feathersjs/feathers-mongoose#55]
So I have a user model which disallow the duplicated username
```js
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

var userSchema = new Schema({
  username: {
      type: String,
      required: true,
      index: {unique: true, dropDups: true}
  },
  password: {type: String, required: true},
  createdAt: {type: Date, 'default': Date.now},
  ExpiredAt: {type: Date}
});

var userModel = mongoose.model('user', userSchema);
module.exports = userModel;
```

I was using `feathers-authentication`, basically following the example in the doc
```js
var app = feathers()
    .configure(feathers.rest())
    .configure(hooks())
    .use(bodyParser.json())
    .use(bodyParser.urlencoded({ extended: true }))
    .configure(authentication({
        secret: '12345'
    }));

mongoose.Promise = global.Promise;
mongoose.connect('mongodb://localhost:27017/user');


app.use('/', service({Model: userModel}));

var userService =  app.service('/');

userService.before(
    {
        create: [authHooks.hashPassword('password')]
    }
)
```

Once I create the second identical user, I got the stack trace on both node console and http response

```
MongoError: E11000 duplicate key error index: user.users.$username_1  dup key: { : "wuyuanyi" }
    at Function.MongoError.create (/home/wuyuanyi/riddle-web/node_modules/mongodb-core/lib/error.js:31:11)
    at toError (/home/wuyuanyi/riddle-web/node_modules/mongodb/lib/utils.js:114:22)
    at /home/wuyuanyi/riddle-web/node_modules/mongodb/lib/collection.js:604:23
    at handleCallback (/home/wuyuanyi/riddle-web/node_modules/mongodb/lib/utils.js:96:12)
    at /home/wuyuanyi/riddle-web/node_modules/mongodb/lib/bulk/unordered.js:470:9
    at handleCallback (/home/wuyuanyi/riddle-web/node_modules/mongodb/lib/utils.js:96:12)
    at resultHandler (/home/wuyuanyi/riddle-web/node_modules/mongodb/lib/bulk/unordered.js:417:5)
    at /home/wuyuanyi/riddle-web/node_modules/mongodb-core/lib/wireprotocol/2_4_support.js:554:17
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```
I read that `feathers-errors` will properly handle the error and return a json object for client handling. What should I do to enable this feature?

**Comment by daffl** [comment]
You can either use our [app generator](https://github.com/feathersjs/generator-feathers) to initialize a new application or use the error handler middleware described [here in the documentation](http://docs.feathersjs.com/middleware/express.html#error-handling).

**Comment by wuyuanyi135** [comment]
Thank you :+1:
