### ISSUE TITLE
What is the best way for validate mongoose models?

### ISSUE THREAD

**Issue by kulakowka** [feathersjs/feathers-mongoose#57]
Validation with [validator.js](https://github.com/guillaumepotier/validator.js) is not working, because library api has changed. 

I think you need to update [documentation about mongoose validations](http://docs.feathersjs.com/databases/mongoose.html#validation) and add examples using [mongoose-validators](https://www.npmjs.com/package/mongoose-validators), [mongoose-unique-validator](https://www.npmjs.com/package/mongoose-unique-validator) or do you have another way?

**Comment by jamesjnadeau** [comment]
Personally, I'm just using the built in validation that mongoose provides. Any errors get passed back to the api the way you'd expect in an express app.

The thing is, feathers doesn't really force you to use a particular validation method! You can go about this whatever way you choose. 

`feathers-hooks` or `hooks` is the recommended way, and perhaps where I would steer you to look/think about this first. If you can create a hook that validates, I think you'll understand the concepts to use any validation option you choose.

**Comment by kulakowka** [comment]
Thank you @jamesjnadeau for quick reply. 

I also prefer to validate models with the help of hooks, because the database may change over time and there is not any guarantee that the new database will support the old validation.

I'll try to do it myself. Could you show an example of a hook for user validation?

**Comment by ekryski** [comment]
@kulakowka Were you going off of these docs? http://docs.feathersjs.com/databases/mongoose.html#validation

If so and they are out of date I can update them pretty quick or feel free to create a PR :smile: 

Generally though I agree with @jamesjnadeau that hooks are a better (more flexible) solution. http://docs.feathersjs.com/help/faq.html#how-do-i-do-validation

**Comment by kulakowka** [comment]
I tried a few different libraries:
- [hapijs/joi](https://github.com/hapijs/joi)
- [chriso/validator.js](https://github.com/chriso/validator.js)
- [mafintosh/is-my-json-valid](https://github.com/mafintosh/is-my-json-valid)
- [zaggino/z-schema](https://github.com/zaggino/z-schema)
- [epoberezkin/ajv](https://github.com/epoberezkin/ajv)
- [flatiron/revalidator](https://github.com/flatiron/revalidator)

Make the choice was not so easy.

I stopped at [revalidate](https://github.com/flatiron/revalidator). 

I would be grateful if you could share your experience in real-world applications.

**Comment by kulakowka** [comment]
@ekryski I read all the pages of the documentation several times. I understood the main points. But as always - the devil is in the details :)

**Comment by kulakowka** [comment]
I'm looking for an elegant way to create validations, not to write a lot of code and still be flexible.

**Comment by ekryski** [comment]
I'll see what I can cook up for an example. I personally have used either validator.js or joi. Usually validator.js because that's what seqelize uses internally.

@kulakowka what was the issue you were running into with the mongoose validation example? I'd like to fix it so that others don't run into it as well.

**Comment by kulakowka** [comment]
@ekryski there was a messed up the name of the library. You can find more info in my PR: https://github.com/kulakowka/feathers-docs/commit/379d3081a0ddd7751199101e2511c22ffef3cf74

**Comment by kulakowka** [comment]
I made a small utility for validation. Under the hood is used [revalidator](https://github.com/flatiron/revalidator). 

I'll be glad if you take a look at my code. Here's what I got:
`/src/utils/jsonValidator.js`

```javascript
import revalidator from 'revalidator'
import errors from 'feathers-errors'

module.exports = function jsonValidator (hook, schema) {
  let result = revalidator.validate(hook.data, schema)

  if (result.valid) return Promise.resolve(hook)

  let error = new Error(schema.message || 'Validation failed')

  error.errors = result.errors.map(error => {
    return {
      path: error.property,
      value: hook.data[error.property],
      message: `${error.property} ${error.message}`
    }
  })

  return Promise.reject(new errors.BadRequest(error, hook.data))
}
```

`/src/services/user/hooks/validate.js`

```javascript
import jsonValidator from '../../../utils/jsonValidator'

var schema = {
  message: 'User validation failed',
  properties: {
    username: {
      type: 'string',
      required: true,
      maxLength: 20,
      minLength: 3
    },
    email: {
      type: 'string',
      format: 'email',
      required: true
    },
    password: {
      type: 'string',
      required: true,
      minLength: 7
    }
  }
}

module.exports = function validateUser (hook) {
  return jsonValidator(hook, schema)
}
```

That's what happens when you run a query with non-valid parameters:
![2016-02-19 22 28 40](https://cloud.githubusercontent.com/assets/557190/13186870/307c8f06-d759-11e5-85bf-5a788ff27dac.png)

I think this is similar to the standard error, which generates a feathersjs. 

I plan to still think about architecture. I think this is not the final version.

**Comment by ekryski** [comment]
@kulakowka That's great man! Exactly what I was thinking. I was actually thinking we might want something like that as a `validateData()` hook that comes bundled with `feathers-hooks`.

and ya you are mapping the validation errors exactly the way mongoose and sequelize errors get returned. Nice work! :smile:

**Comment by ekryski** [comment]
@kulakowka the way we normally create hooks is they are wrapped in a function so you can pass options. If I were to make that generic I would probably just do this:

```js
import errors from 'feathers-errors'

export default function jsonValidator(validator, schema) {
  return function(hook) {
    let result = validator.validate(hook.data, schema)

    if (result.valid) return Promise.resolve(hook)

    let error = new Error(schema.message || 'Validation failed')

    error.errors = result.errors.map(error => {
      return {
        path: error.property,
        value: hook.data[error.property],
        message: `${error.property} ${error.message}`
      }
    })

    throw new errors.BadRequest(error, hook.data);
  } 
}
```

Then you could just call it like this `jsonValidator(revalidator, schema)`.

**Comment by kulakowka** [comment]
Yes, I thought about how to move this code in a separate project (or in `feathers-hooks` if you want). But I want to make a beautiful and concise hook. So I will not be in a hurry. In simple cases, it works. But I would like to explore more different situations.

**Comment by ekryski** [comment]
@kulakowka if you want to do a PR to `feathers-hooks` as a bundled hook that would be sweet. Even this is a great start. If you don't I will :wink:

**Comment by daffl** [comment]
We could just create a `feathers-validations` repository.

**Comment by ekryski** [comment]
@daffl not sure I see the point of having a whole repo for probably just a couple hooks. I might be missing something??

If we are smart this could actually be used client side as well. So you could just share validations/hooks if you want.

**Comment by kulakowka** [comment]
I never took part in open source projects. I think it's better if you do this. :+1:

**Comment by ekryski** [comment]
@kulakowka don't worry. You're already helping and doing great! We're friendly :smile:  You should do it. 

If you copy paste what I did above then that should work nicely for a generic validation hook. I can write the tests around it.

**Comment by kulakowka** [comment]
@ekryski revalidator is a cross-browser / node.js validator. I think it can be used on the client side. But I have not tested this.

**Comment by ekryski** [comment]
@kulakowka I'm pretty sure `validator.js` and `joi` can as well so supporting 3 different validation libs should definitely be good for the first round.

**Comment by daffl** [comment]
Oh @ekryski sorry, I thought it would add a validator.js dependency. That hook in there is totally fine then. I'm wondering if we could also just have a separate module that provides a collection of validation hooks using a specific library (revalidator, validator.js) that works on all platforms.

@kulakowka Too late, you're already taking part :) We're here to help and hopefully didn't make contributing too hard.

**Comment by kulakowka** [comment]
I agree with @daffl. A separate module for the validation - it sounds good.

**Comment by ekryski** [comment]
Alright so @daffl and I chatted in Slack. I think what we're probably going to do is roll this in as a bundled hook inside of `feathers-hooks` for now. Then at a later date we'll probably break out a lot of the bundled hooks we have into their own plugin(s).

**Comment by kulakowka** [comment]
I found most popular packages:
- [is-my-json-valid](https://www.npmjs.com/package/is-my-json-valid) 5 918 029 downloads in the last month
- [validator](https://www.npmjs.com/package/validator) 902 596 downloads in the last month
- [joi](https://www.npmjs.com/package/joi) 861 354 downloads in the last month

I think we can consider them to begin.
I tried using joi - it works perfectly. But looks ugly and redundant. Although this is a matter of taste. 
I think it is necessary to provide support for the most popular libraries for validation.

**Comment by ekryski** [comment]
:+1: that `is-my-json-valid` download count is blowing my mind right now

**Comment by kulakowka** [comment]
Oh, yes, I am also surprised. :scream:

**Comment by kulakowka** [comment]
I have tried all of these packages. But [revalidator](https://github.com/flatiron/revalidator) the easiest in my opinion.

**Comment by kulakowka** [comment]
I also started [feathers-validate-hook](https://github.com/kulakowka/feathers-validate-hook). When i will finish it should solve this problem %)

**Comment by shyambca123** [comment]
module.exports = function validateUser (hook) {
  return jsonValidator(hook, schema)
}

In this where you defined hook . am getting this issue
<pre>TypeError: Cannot convert undefined or null to object
            <br> &nbsp; &nbsp;at Function.keys (&lt;anonymous&gt;)
            <br> &nbsp; &nbsp;at validateObject (D:\xampp\htdocs\mean\node_modules\revalidator\lib\revalidator.js:176:34)
            <br> &nbsp; &nbsp;at Object.validate (D:\xampp\htdocs\mean\node_modules\revalidator\lib\revalidator.js:35:7)
            <br> &nbsp; &nbsp;at jsonValidator (D:\xampp\htdocs\mean\utils\jsonValidator.js:5:28)
            <br> &nbsp; &nbsp;at Object.validateUser (D:\xampp\htdocs\mean\modules\RestApi\Services\user.service.js:33:10)
            <br> &nbsp; &nbsp;at validationSignup (D:\xampp\htdocs\mean\modules\RestApi\Controllers\users.controller.js:35:14)
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\xampp\htdocs\mean\node_modules\express\lib\router\layer.js:95:5)
            <br> &nbsp; &nbsp;at next (D:\xampp\htdocs\mean\node_modules\express\lib\router\route.js:137:13)
            <br> &nbsp; &nbsp;at Route.dispatch (D:\xampp\htdocs\mean\node_modules\express\lib\router\route.js:112:3)
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\xampp\htdocs\mean\node_modules\express\lib\router\layer.js:95:5)
            <br> &nbsp; &nbsp;at D:\xampp\htdocs\mean\node_modules\express\lib\router\index.js:281:22
            <br> &nbsp; &nbsp;at Function.process_params (D:\xampp\htdocs\mean\node_modules\express\lib\router\index.js:335:12)
            <br> &nbsp; &nbsp;at next (D:\xampp\htdocs\mean\node_modules\express\lib\router\index.js:275:10)
            <br> &nbsp; &nbsp;at Function.handle (D:\xampp\htdocs\mean\node_modules\express\lib\router\index.js:174:3)
            <br> &nbsp; &nbsp;at router (D:\xampp\htdocs\mean\node_modules\express\lib\router\index.js:47:12)
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (D:\xampp\htdocs\mean\node_modules\express\lib\router\layer.js:95:5)
        </pre>
