### ISSUE TITLE
Validation error should be returned as JSON

### ISSUE THREAD

**Issue by Glavin001** [feathersjs/feathers-mongoose#6]
Error:

```
ValidationError: Path `field` is required.
    at model.Document.invalidate (/Users/glavin/Development/repo/node_modules/mongoose/lib/document.js:1009:32)
    at /Users/glavin/Development/repo/node_modules/mongoose/lib/document.js:958:16
    at validate (/Users/glavin/Development/repo/node_modules/mongoose/lib/schematype.js:610:7)
    at /Users/glavin/Development/repo/node_modules/mongoose/lib/schematype.js:627:9
    at Array.forEach (native)
    at SchemaString.SchemaType.doValidate (/Users/glavin/Development/repo/node_modules/mongoose/lib/schematype.js:614:19)
    at /Users/glavin/Development/repo/node_modules/mongoose/lib/document.js:956:9
    at process._tickCallback (node.js:415:13)
```

Should be:

```json
{
   errors: [{
     "ValidationError: Path `isolationPoint` is required., Path `tagNum` is required., Path `asset` is required."
   }]
}
```

**Comment by ekryski** [comment]
Confirmed this is works with `feathers-errors` and was fixed with PR #18.
